Connection:
    Domain: https://upmcenterprises.atlassian.net
    Username: wellsj7@upmc.edu
    Password:
Query: project = myupmc or project = rocket or project = horizon or project = gemini or project = imperial or project = Nova

Workflow: 
    Closed: Closed
    Code Review: Code Review
    Complete: Complete 
    New: New
    Pre-Grooming: Pre-Grooming
    Grooming: Grooming
    Ready:
    - Ready
    - To Do
    In Progress:
    - In-Progress
    - In Progress
    Design Review:
    - Design-Review
    - Design Review
    Dev Review:
    - Dev-Review
    - Dev Review
    - Review
    Dev Complete:
    - Dev Complete
    - Ready for QA
    QA:
    - QA
    - Integration/Testing
    - Testing
    Done: Done
    Accepted: Accepted
    Backlog: backlog

Output:

    # CSV files with raw data for input to other tools or further analysis in a spreadsheet
    # If you use .json or .xlsx as the extension, you can get JSON data files or Excel
    # spreadsheets instead

    Cycle time data:
    - cycletime.csv
    - cycletime.json
    CFD data: cfd.csv
    Scatterplot data: scatterplot.csv
    Histogram data: histogram.csv
    Throughput data: throughput.csv
    Percentiles data: percentiles.csv

    # Various charts

    Scatterplot chart: scatterplot.png
    Scatterplot chart title: Cycle time scatter plot
    
    Histogram chart: histogram.png
    Histogram chart title: Cycle time histogram
    
    CFD chart: cfd.png
    CFD chart title: Cumulative Flow Diagram
    
    Throughput chart: throughput.png
    Throughput chart title: Throughput trend
    
    Burnup chart: burnup.png
    Burnup chart title: Burn-up

    Burnup forecast chart: burnup-forecast.png
    Burnup forecast chart title: Burn-up forecast
    Burnup forecast chart trials: 100 # number of Monte Carlo trials to run to estimate completion date

    # Burnup forecast chart throughput window: 60 # Days in the past to use for calculating historical throughput
    # Burnup forecast chart throughput window end: 2018-06-01 # Calculate throughput window to this date (defaults to today)
    # Burnup forecast chart target: 100 # items to complete in total; by default uses the current size of the backlog
    # Burnup forecast chart deadline: 2018-06-01 # deadline date, in ISO format; if not set, no deadline is drawn.
    # Burnup forecast chart deadline confidence: .85 # percentile to use to compare forecast to deadline
    
    WIP chart: wip.png
    WIP chart title: Work in Progress

    Ageing WIP chart: ageing-wip.png
    Ageing WIP chart title: Ageing WIP

    Net flow chart: net-flow.png
    Net flow chart title: Net flow